### ISSUE TITLE
Dashboard fails to load workspace: Failed to decode all mod hcl files

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-mod-net-insights#21]
**Describe the bug**

```
steampipe-mod-net-insights$ steampipe dashboard 
[ Wait    ] Loading Workspace
Error: failed to load workspace: Failed to decode all mod hcl files
Mod defines more than one resource named 'net_insights.input.domain_input': 
- ../steampipe-mod-net-insights/dashboards/ssl_certificate_report.sp:17,3-23
-../steampipe-mod-net-insights/dashboards/ssl_configuration_report.sp:11,3-23
steampipe-mod-net-insights$
```

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by misraved** [comment]
Tested the plugin with Steampipe CLI `v0.20.11`, and the issue no longer exists 👍.
